name: Model Training Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup directories
      run: |
        mkdir -p models
        mkdir -p data/raw
        mkdir -p data/processed
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
        
    - name: Train model
      run: |
        python train.py
        
    - name: Update Accuracy Badge
      run: |
        ACCURACY=$(python -c "
        import glob
        import torch
        latest_model = max(glob.glob('models/*.pkl'), key=lambda x: torch.load(x)['timestamp'])
        accuracy = torch.load(latest_model)['accuracy']
        print(f'{accuracy:.2f}')
        ")
        
        echo "{
          \"schemaVersion\": 1,
          \"label\": \"accuracy\",
          \"message\": \"${ACCURACY}%\",
          \"color\": \"blue\"
        }" > accuracy.json
        
    - name: Deploy Badge
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: .
        branch: badges
        target-folder: .
        clean: false
        files: accuracy.json

    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/*.pkl